"""Add banking details to Fixer model

Revision ID: 1d026e279ba6
Revises: 53f36c97a0c4
Create Date: 2025-07-10 22:13:13.320725

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d026e279ba6'
down_revision = '53f36c97a0c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fixers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bank_account_holder', sa.String(length=150), nullable=True))
        batch_op.drop_column('bank_branch_code')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fixers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bank_branch_code', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
        batch_op.drop_column('bank_account_holder')

    # ### end Alembic commands ###
