"""Add DataInsight table

Revision ID: 35caa6a45075
Revises: d21a3ecbf594
Create Date: 2025-06-30 07:19:16.364482

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '35caa6a45075'
down_revision = 'd21a3ecbf594'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data_insights',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('insight_text', sa.Text(), nullable=False),
    sa.Column('generated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('area', sa.String(length=100), nullable=True))
        batch_op.drop_column('longitude')
        batch_op.drop_column('latitude')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('latitude_cache')
        batch_op.drop_column('longitude_cache')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('longitude_cache', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('latitude_cache', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))

    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('latitude', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('longitude', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.drop_column('area')

    op.drop_table('data_insights')
    # ### end Alembic commands ###
