"""Add location fields to Fixer model

Revision ID: 49369363c59a
Revises: 7ff6a7d9affb
Create Date: 2025-06-30 16:15:20.673214

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49369363c59a'
down_revision = '7ff6a7d9affb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fixers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('current_latitude', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('current_longitude', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fixers', schema=None) as batch_op:
        batch_op.drop_column('current_longitude')
        batch_op.drop_column('current_latitude')

    # ### end Alembic commands ###
