"""Add balance and banking details to Fixer model

Revision ID: 53f36c97a0c4
Revises: fc948c6d1f03
Create Date: 2025-07-10 01:29:33.087090

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '53f36c97a0c4'
down_revision = 'fc948c6d1f03'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fixers', schema=None) as batch_op:
        # --- THIS IS THE CORRECTED LINE ---
        # It now tells the database to use '0.00' as the default for existing rows.
        batch_op.add_column(sa.Column('balance', sa.Numeric(precision=10, scale=2), server_default=sa.text('0.00'), nullable=False))
        batch_op.add_column(sa.Column('bank_name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('bank_account_number', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('bank_branch_code', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fixers', schema=None) as batch_op:
        batch_op.drop_column('bank_branch_code')
        batch_op.drop_column('bank_account_number')
        batch_op.drop_column('bank_name')
        batch_op.drop_column('balance')

    # ### end Alembic commands ###
