"""Add fixer fee status field model

Revision ID: 84a9b66f328b
Revises: 5792e4b8bff3
Create Date: 2025-07-01 06:45:08.717364

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '84a9b66f328b'
down_revision = '5792e4b8bff3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        # --- THIS IS THE CORRECTED LINE ---
        # It now tells the database to use 'unpaid' as the default for existing rows.
        batch_op.add_column(sa.Column('fixer_fee_status', sa.String(length=50), server_default='unpaid', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.drop_column('fixer_fee_status')

    # ### end Alembic commands ###
