"""Remove client payment fields from Job model

Revision ID: a63b5daceddf
Revises: def8beb40e11
Create Date: 2025-07-03 00:40:35.363838

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a63b5daceddf'
down_revision = 'def8beb40e11'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.drop_column('amount')
        batch_op.drop_column('payment_status')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('service_request_cache',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('service_request_cache',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)

    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payment_status', sa.VARCHAR(length=50), server_default=sa.text("'unpaid'::character varying"), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('amount', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
