"""Add API auth fields to User and Fixer models

Revision ID: ba074560551e
Revises: 1d026e279ba6
Create Date: 2025-07-19 02:47:49.622909

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba074560551e'
down_revision = '1d026e279ba6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fixers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('api_key', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('otp_hash', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('otp_expiry', sa.DateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_fixers_api_key'), ['api_key'], unique=True)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('api_key', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('otp_hash', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('otp_expiry', sa.DateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_users_api_key'), ['api_key'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_api_key'))
        batch_op.drop_column('otp_expiry')
        batch_op.drop_column('otp_hash')
        batch_op.drop_column('api_key')

    with op.batch_alter_table('fixers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fixers_api_key'))
        batch_op.drop_column('otp_expiry')
        batch_op.drop_column('otp_hash')
        batch_op.drop_column('api_key')

    # ### end Alembic commands ###
