"""Add last_assigned_at to Fixer model

Revision ID: be0ce17e37a4
Revises: a63b5daceddf
Create Date: 2025-07-03 01:29:40.808710

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be0ce17e37a4'
down_revision = 'a63b5daceddf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fixers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_assigned_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('jobs', schema=None) as batch_op:
        # --- THIS IS THE CORRECTED LINE ---
        # It now tells the database to use 'unpaid' as the default for existing rows.
        batch_op.add_column(sa.Column('payment_status', sa.String(length=50), server_default='unpaid', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.drop_column('payment_status')

    with op.batch_alter_table('fixers', schema=None) as batch_op:
        batch_op.drop_column('last_assigned_at')

    # ### end Alembic commands ###

