"""Add payment fields to Job model

Revision ID: c19c8672fd6c
Revises: 4263fc820a08
Create Date: 2025-06-24 16:20:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c19c8672fd6c'
down_revision = '4263fc820a08'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=True))
        
        # --- THIS IS THE CORRECTED LINE ---
        # It now tells the database to use 'unpaid' as the default for existing rows.
        batch_op.add_column(sa.Column('payment_status', sa.String(length=50), server_default='unpaid', nullable=False))
        
        batch_op.alter_column('latitude',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
        batch_op.alter_column('longitude',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
        batch_op.alter_column('client_contact_number',
               existing_type=sa.VARCHAR(length=30),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.alter_column('client_contact_number',
               existing_type=sa.VARCHAR(length=30),
               nullable=False)
        batch_op.alter_column('longitude',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
        batch_op.alter_column('latitude',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
        batch_op.drop_column('payment_status')
        batch_op.drop_column('amount')

    # ### end Alembic commands ###
