"""Add is_admin flag to User model

Revision ID: d21a3ecbf594
Revises: c19c8672fd6c
Create Date: 2025-06-26 23:30:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd21a3ecbf594'
down_revision = 'c19c8672fd6c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        # --- THIS IS THE CORRECTED LINE ---
        # It now tells the database to use 'False' as the default for existing rows.
        batch_op.add_column(sa.Column('is_admin', sa.Boolean(), server_default=sa.text('false'), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('is_admin')

    # ### end Alembic commands ###
