"""Add vetting fields to Fixer model

Revision ID: def8beb40e11
Revises: 84a9b66f328b
Create Date: 2025-07-01 11:57:13.740236

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'def8beb40e11'
down_revision = '84a9b66f328b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fixers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('vetting_status', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('id_document_url', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('vetting_notes', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fixers', schema=None) as batch_op:
        batch_op.drop_column('vetting_notes')
        batch_op.drop_column('id_document_url')
        batch_op.drop_column('vetting_status')

    # ### end Alembic commands ###
